### ISSUE TITLE
import/re-export vegawidget functions

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/vlbuildr#10]
Recent versions of `vegawidget` have a function `use_vegawidget()` that is meant for package developers to be able to import and re-export basic `vegawidget` functions, which would let you avoid `library(vegawidget)`.

We use it for `altair`; here's the result: <https://github.com/vegawidget/altair/blob/master/R/utils-vegawidget.R>

This provides you with the basics, and you can snip out whatever you don't want to expose.

Happy to make a PR, if you like.

**Comment by AliciaSchep** [comment]
Thanks for the pointer! I briefly looked at `use_vegawidget`, but then thought it might be for when you have an 's3 class' (should have read the documentation!).  Will add!

**Comment by AliciaSchep** [comment]
Updated to use `use_vegawidget`!  To Do: Figure out whether any of the re-exported functions should be omitted & whether vlbuildr should use its own s3 class(es).

**Comment by ijlyttle** [comment]
🎉Glad it worked!

I recently updated it for the situation where you might not be building your own class.
