### ISSUE TITLE
Travis and automation of pkgdown deployment

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/vlbuildr#11]
In `vegawidget`, `altair`, etc., I've got a system set up (like everything else I do, adapted from Hadley) that will use Travis to build and deploy your pkgdown site with each commit to master.

With your permission, I'd be happy to set it up here.

It would involve:

- creating an orphan `gh-pages` branch to this repository
- adding a public-key for deployment to this repository
- adding a private-key for deployment to Travis
- making a PR into `master` to set the wheels in motion:
  - `.travis.yml` file
  - delete, then gitignore `docs` directory 

I think I have the "authority" to do the first three myself; and I'd be happy to make a PR - also happy to answer any questions.

**Comment by AliciaSchep** [comment]
Thanks @ijlyttle , it sounds like you've developed a great setup for this -- I'd love to learn to mimic that setup. I think I'll try to add this myself and ask for help if/when I get stuck!

**Comment by ijlyttle** [comment]
Happy to help if needed :)

FWIW, there is an automated way to do this, but it involves giving ROpenSci access to the repository.

I have one collaborator who does not feel comfortable doing that (nothing against ROpenSci), so we figured out a manual approach:

Here's some [notes](https://gist.github.com/ijlyttle/2ffe299abd3fab76398cb14e70aa068e) I keep to remind myself of this manual process. Clarification-suggestions welcome!

**Comment by AliciaSchep** [comment]
Was able to follow your notes & get the pkgdown deployment setup -- thanks @ijlyttle !
