### ISSUE TITLE
re Repeat and Resolve

### ISSUE THREAD

**Issue by dinorisi** [vegawidget/vlbuildr#15]
Hi @AliciaSchep,

Magnificent work!  Back in August, I was able to visualize through vlbuildr in R Studio almost all the examples from Vega-Light's example gallery, except those involving "_resolve_" (Bullet Chart, Layered Plot with Dual-Axis, etc.) and "_repeat for columns_".  Many thanks for a great package:   interactive examples with crossfilters and brushing plots to show data on a table are very powerful and not difficult to build! 

Overall, if the parameter documentation for vlbuildr functions relies on descriptions pulled directly from the Vega-Lite schema, examples on the Vega-Light website are straightforward.  Yes, one may make invalid specs anytime, but resources are there to figure out the building blocks required.  

Unfortunately, even with the latest changes in place, the specs with _resolve and repeat col_ are still not working.  I am afraid I am missing something.  Moreover, on the example page [https://vegawidget.github.io/vlbuildr/articles/examples.html](url)  I now see a _repeat wrap_ example with 3 columns only instead of 4 as might have been expected from 
  vl_repeat_wrap("Horsepower", "Miles_per_Gallon", "Acceleration", "Displacement").  One may make it work if a number of columns to add argument is 4, but most likely that may not be an intention.

Thank you.

Dino

**Comment by AliciaSchep** [comment]
Thank Dino, both for your encouraging words and your very helpful bug reports -- I was able to reproduce the issues with 'repeat' and 'resolve' and will put forward a fix for those soon. 

One of my next goals for this project is to put together a full example gallery covering all the 'Vega-Lite' examples as that will likely be a good way to test the package and identify bugs (as you have done!).  If you have code for all the examples you have worked through and would have any interest in sharing, I would love to be able to build off of your work for that example gallery! (And would of course credit you for the effort!)
