### ISSUE TITLE
vl_facet wrap defaults and vl_add_properties changes

### ISSUE THREAD

**Issue by dinorisi** [vegawidget/vlbuildr#17]
Hi Alicia,

Thank you very much for making a quick fix on _**repeat**_ and _**resolve**_.  New charts are possible!  

Tried to put together some visualizations and spotted changes that affected chart rendering under the new version in some cases.  Please see attached (old version-based charts, codes and comments).  
[vlbuildr_set01_old_vs_new.pdf](https://github.com/vegawidget/vlbuildr/files/3613425/vlbuildr_set01_old_vs_new.pdf)

_**vl_facet_wrap**_ seems not to have any longer columns as default.
_**vl_add_properties**_ seems not to allow some modifications previously possible. 

Some charts like trellis chart Becker's Barley Trellis Plot, Horizontal Stacked Chart with Text overlay, bar chart with mini map _work under the old version_, but _will not visualize under the new_ one or _will modify the appearance / element position_.  

Thank you.

**Comment by AliciaSchep** [comment]
vl_facet_wrap and vl_add_properties should now be fixed, so closing this... #18 brings up some additional issues so will keep that open
