### ISSUE TITLE
bug: nominal x-axis is grouped as undefined when variable name contains a dot

### ISSUE THREAD

**Issue by theunis** [vegawidget/vlbuildr#27]
Example, taking `variable.one` as a variable:
```r
df <- data.frame(variable.one = c(1, 2, 3), 
                 variable_two = c(1, 2, 3), 
                 value = c(0.1, 0.2, 0.3))

vlbuildr::vl_chart() %>% 
  vlbuildr::vl_add_data(values = df) %>% 
  vlbuildr::vl_encode_x('variable.one', "nominal") %>% 
  vlbuildr::vl_encode_y('value', "quantitative") %>% 
  vlbuildr::vl_mark_point()
```
![afbeelding](https://user-images.githubusercontent.com/2880232/66827681-7f608e80-ef4f-11e9-9c12-22de6d92406c.png)

While it works correctly with the variable `variable_two`
```r
vlbuildr::vl_chart() %>% 
  vlbuildr::vl_add_data(values = df) %>% 
  vlbuildr::vl_encode_x('variable_two', "nominal") %>% 
  vlbuildr::vl_encode_y('value', "quantitative") %>% 
  vlbuildr::vl_mark_point()
```
![afbeelding](https://user-images.githubusercontent.com/2880232/66827654-6fe14580-ef4f-11e9-9427-170957ea19b3.png)

**Comment by dinorisi** [comment]
Hi, I think Alicia may elaborate on that a bit further.   However, since in Vega dots and brackets [ ] may be used to access nested objects, a workaround (same as in Vega-Light) would be to use \\\\ to escape them.
```
df <- data.frame(variable.one = c(1, 2, 3), 
                 variable_two = c(1, 2, 3), 
                 value = c(0.1, 0.2, 0.3))

vlbuildr::vl_chart() %>% 
  vlbuildr::vl_add_data(values = df) %>% 
  vlbuildr::vl_encode_x('variable\\.one', "nominal") %>% 
  vlbuildr::vl_encode_y('value', "quantitative") %>% 
  vlbuildr::vl_mark_point()
```

**Comment by theunis** [comment]
Thanks, that workaround should work for me.
Maybe add in an informative warning to the user when this happens?

**Comment by AliciaSchep** [comment]
Thanks @dinorisi for sharing the workaround!

A warning would be good, although I think it should be equally possible and better for the package to automatically add the escaping! dots in column names are common enough among R data.frames to make this a worthwhile feature

**Comment by AliciaSchep** [comment]
Should now be fixed in latest master branch!
