### ISSUE TITLE
Layered Views to Facet

### ISSUE THREAD

**Issue by dinorisi** [vegawidget/vlbuildr#29]
Hi @AliciaSchep !

Not a bug, but what would be vlbuildr`s approach to _layered views to facet_?   In the file attached it is the last example; however, it is done in vegawidget.  
[set03_vlbuildr.txt](https://github.com/vegawidget/vlbuildr/files/3771027/set03_vlbuildr.txt)
 In vlbuildr, I see some workaround with shortcuts, but through v/h/concat.

Note:  Something might have happened to website`s _charts / visuals for _**repeat**_ .  Looks like they are not rendered properly_ (ex.  Interactive Scatterplot matrix, etc.).  https://vegawidget.github.io/vlbuildr/articles/examples.html

**Comment by AliciaSchep** [comment]
Thanks will look into the layer + facet questions... re the `repeat` issue that was a bug introduced by the fix to "." (#27 )... not sure why I didn't catch that when looking at examples locally... guess it reinforces need for a better regression testing setup (#25).  Will fix that one soon.

**Comment by AliciaSchep** [comment]
So with latest version the following works:

```r
heatmap <- vl_chart() %>%
  vl_encode_color(aggregate = "count", type = "Q") %>%
  vl_scale_color(scheme = "darkred") %>%
  vl_encode_x(field = "Cylinders:O") %>%
  vl_scale_x(paddingInner = 0) %>%
  vl_encode_y(field = "Year:O") %>%
  vl_scale_x(paddingInner = 0) %>%
  vl_mark_rect()

text <- vl_chart() %>%
  vl_encode_color(value = "white") %>%
  vl_encode_x(field = "Cylinders:O") %>%
  vl_encode_y(field = "Year:O") %>%
  vl_encode_text(aggregate = "count", type = "Q") %>%
  vl_mark_text(baseline = "middle")

vl_layer(heatmap, text) %>%
  vl_add_data_url("https://vega.github.io/vega-editor/app/data/cars.json") %>%
  vl_facet_column(field = "Origin", type = "nominal") 
```

(Note: Latest version on github does have some breaking changes, due to an upgrade to VL 4.0)
