### ISSUE TITLE
Move to vegawidget org?

### ISSUE THREAD

**Issue by AliciaSchep** [vegawidget/vlbuildr#6]
@ijlyttle would it be okay if I move this repo to the 'vegawidget' org?

**Comment by ijlyttle** [comment]
Of course! Please let me know if I need to do anything to help make that happen 🎉

**Comment by AliciaSchep** [comment]
Seemed to have been able to move the repo! :tada:

**Comment by AliciaSchep** [comment]
So I moved it successfully, but now I seem to not have permission to edit the 'tagline/link' at the top anymore! @ijlyttle I am guessing you have 'admin' rights now -- would you be able to look into the permissions for this repo?  (The change I want to make right now is update the link to right url post-move!)

**Comment by ijlyttle** [comment]
Welcome 🚀

I have set your permissions to admin for this repo, which (I hope) will do the trick. Please let me know if I can do anything else.

**Comment by AliciaSchep** [comment]
Yes, that did the trick :raised_hands: Thank you @ijlyttle !
