### ISSUE TITLE
Calling `vl_config_range()` throws `Error: No method asJSON S3 class: name`

### ISSUE THREAD

**Issue by kcole-rsn** [vegawidget/vlbuildr#79]
I'm trying to define a custom color scheme to be used for categorial and ramp ranges in my charts like so:

```r
vl_chart() %>%
  vl_add_data(values = mtcars) %>%
  vl_mark_point() %>%
  vl_encode_x(field = 'wt', type = 'quantitative') %>%
  vl_encode_y(field = 'mpg', type = 'quantitative') %>%
  vl_config_range(category = c("blue", "green", "red"))

```

However, the chart fails to render with the error `Error: No method asJSON S3 class: name`. I thought it was perhaps related to the way that I am trying to define my color arrays, but the same error is thrown as soon as `vl_config_range()` is called, even if its arguments are left empty like so:

```r
vl_chart() %>%
  vl_add_data(values = mtcars) %>%
  vl_mark_point() %>%
  vl_encode_x(field = 'wt', type = 'quantitative') %>%
  vl_encode_y(field = 'mpg', type = 'quantitative') %>%
  vl_config_range()

```

Am I perhaps just not defining my color arrays correctly? The equivalent in Vega-Lite JSON works:
```json
{
    "config": {
        "range": {
            "category": ["blue", "green", "red"]
        }
    }
}        

```

**Comment by AliciaSchep** [comment]
Seems like there is a bug that's generally impacting `vl_config_range` regardless of arguments.  Will put in a fix.  With current version prior to bug fix, you could instead of using `config` do something like:

```
vl_chart() %>%
    vl_add_data(values = mtcars) %>%
    vl_mark_point() %>%
    vl_encode_x(field = 'wt', type = 'quantitative') %>%
    vl_encode_y(field = 'mpg', type = 'quantitative') %>%
    vl_encode_color("cyl:N", scale = list(range = c("blue", "green", "red"))) 
```

**Comment by kcole-rsn** [comment]
Thanks for taking a look!

I just also realized that defining the range within `vl_config()` works as expected:
```r
vl_config(range = list(category = list(“green”, “blue”)))
```

That’s super helpful, as I’m then able to define a generally applicable “theme” via a config as was my goal—although it’s somewhat less readable.
